#!/bin/bash
# $1: .patch file
# $2: --nol for coverletter (no list)

RESULT=$(grep -e "^Acked-by" -e "^Suggested-by:" -e "^Reviewed-by:" -e "^Signed-off-by:" -e "^Tested-by:" -e "^Reported-by:" -e "^Cc:" -e "^Reported-and-tested-by:" $1 | cut -f 2 -d ':')
if [ "$RESULT" != "" ]; then
	echo "$RESULT"
fi

scripts/get_maintainer.pl --nogit --nogit-fallback --norolestats --nom --nor $2 $1
