#!/bin/bash
# $1: .patch file

RESULT=$(grep -e "^Acked-by" -e "^Suggested-by:" -e "^Reviewed-by:" -e "^Signed-off-by:" -e "^Tested-by:" -e "^Reported-by:" -e "^Cc:" -e "^Reported-and-tested-by:" $1 | cut -f 2 -d ':'| sed -e 's/^ *//g' | sed -e 's/ *#.*//g')
if [ "$RESULT" != "" ]; then
	echo "$RESULT"
fi

scripts/get_maintainer.pl --nogit --nogit-fallback --norolestats --nom --nor $1
#scripts/get_maintainer.pl --nogit --nogit-fallback --norolestats --nom --nor --pattern-depth=1 $1
