#!/bin/bash

RESULT=$(grep -e "^Acked-by" -e "^Suggested-by:" -e "^Reviewed-by:" -e "^Signed-off-by:" -e "^Tested-by:" -e "^Reported-by:" -e "^Cc:" -e "^Reported-and-tested-by:" $1 | cut -f 2 -d ':')
if [ "$RESULT" != "" ]; then
	echo "$RESULT"
fi

if [ $1 == "0000-cover-letter.patch" ]; then
	cat ~/scripts/mycoverletterlist.txt
else
	scripts/get_maintainer.pl --nogit --nogit-fallback --norolestats --nom --nor $1
fi
