#!/bin/bash
#
# $1 = TO or CC

FILE="/tmp/tocclist.txt"

> $FILE

for f in *.patch
do
	if [ $f != "0000-cover-letter.patch" ]; then
		~/scripts/_tocmd  $f >> $FILE
		~/scripts/_cccmd $f >> $FILE
	fi
done

cat $FILE | sort | uniq
