#!/bin/bash
#
# $1 = TO or CC

FILE="/tmp/tocclist.txt"

> $FILE

for f in *.patch
do
	if [ $f != "0000-cover-letter.patch" ]; then
		if [ $1 == "TO" ];
		then
			~/scripts/_tocmd  $f >> $FILE
		else
			~/scripts/_cccmd $f --nol >> $FILE
		fi
	fi
done

cat $FILE | sort | uniq
