#!/bin/bash
#
# $1 = TO or CC

if [ $COVER_CC != "1" ]; then
	exit
fi

FILE="/tmp/tocclist.txt"

> $FILE

for f in *.patch
do
	if [ $f != "0000-cover-letter.patch" ]; then
		if [ $1 == "TO" ]; then
			~/scripts/_tocmd  $f >> $FILE
		else
			~/scripts/_cccmd $f >> $FILE
		fi
	fi
done

cat $FILE | sort | uniq
