#!/bin/bash
alias gb='git branch'
alias gba='gb -a'
alias gco='git checkout'
alias gcob='gco -b'

alias ga='git add'
alias gd='git diff'
alias gdc='git diff --cached'
alias gc='git cherry-pick'
alias gl='git log '
alias glo='gl --oneline'
alias glome='glo --author=viresh'
alias glor='glo --reverse'
alias gloo='gl --pretty=onelin'
alias glf='gl --pretty=fixes'
alias gls='gl --stat'
alias glsp='gls -p'
alias glspr='glsp --reverse'
alias glspme='glsp --author=viresh'
alias gs='git status'
alias gsh='git show --stat -p'
alias gca='git commit --amend'
alias gcf='git commit --fixup'
alias tgca='GIT_EDITOR=cat gca'
alias tgrevert='GIT_EDITOR=cat git revert'
alias gcah='gca -C HEAD'
alias gcara='gcah --reset-author'
alias gcdc='git commit --date="`date`" -c '
alias gampcp='mv /media/psf/Home/Documents/[1-9].txt ~/Downloads/patches/'
alias gamp='git am -3 ~/Downloads/patches/*'
alias cgamp='dos2unix ~/Downloads/patches/*'
alias dgamp='rm -rf ~/Downloads/patches/*'

alias gr='git rebase -i'
alias tgr='GIT_EDITOR=cat gr'
alias gra='gr --autosquash'
alias tgra='GIT_EDITOR=cat gra'
alias gro='gr origin/master'
alias grao='gra origin/master'
alias grh='git reset --hard '
alias grhm='git reset --hard origin/master'
alias grs='git rebase --skip'
alias grc='git rebase --continue'
alias tgrc='GIT_EDITOR=cat grc'

alias grv='git remote -v'

alias gf='git fetch -p'
alias gfo='gf -p origin'
alias gfs='gf -p self'
alias gp='git push -f'
alias gp='git push -f'
alias gpa='git push --mirror'
alias gpo='gp origin '
alias gpl='gp linaro '
alias gps='git push self --mirror'

alias ggrep='git grep'
alias gk='gitk --all -100&'

alias cpatch='scripts/checkpatch.pl --strict'
alias acpatcha='../../devel/linux/scripts/checkpatch.pl --strict *.patch'
alias cpatcha='cpatch *.patch'
alias gpatch='git format-patch -C -M --thread=shallow'
alias gpatchc='gpatch --cover-letter'
gpatchcs() { gpatchc --subject-prefix="PATCH V$1" $2; }
alias ph='gpatch HEAD^'
phc() { gpatch $1^..$1; }
rpull() { git request-pull remotes/linux-linaro/linux-linaro-core-tracking git://git.linaro.org/arm/big.LITTLE/mp.git $1 > ../pull.txt; gvim ../pull.txt; }
cpufreqrpull() { git request-pull origin/master git://git.linaro.org/people/vireshk/linux.git $1 > ../pull.txt; gvim ../pull.txt; }

alias gitgetcclist='for i in `cat ../test`; do gls HEAD~200.. -- $i > ../pull.txt;echo $i; cat ../pull.txt | grep -e Acked -e Cc | sort -u; echo ""; done | less'

alias mmcmail='git send-email --to=linux-mmc@vger.kernel.org'
alias armmail='git send-email --to=linux-arm-kernel@lists.infradead.org '
#rmk patch tracker mail
alias armpatchmail='git send-email --to=patches@arm.linux.org.uk'

alias linarorebase='/home/viresh/scripts/linarorebase.sh rebase'
alias linaroclrrebase='/home/viresh/scripts/linarorebase.sh clear_rebase'
alias linaropush='/home/viresh/scripts/linarorebase.sh push'
alias linarostat='/home/viresh/scripts/linarorebase.sh stat'
alias linarocheck='/home/viresh/scripts/linarorebase.sh check'
#alias mypatchcountrank='gl --no-merges --format="%aN" v3.12..lnext/master | sort | uniq -ic| sort -nr | less'
#alias mypatchcount='glo  --author=viresh --no-merges origin/master | wc -l'
mypatch() { glo  --author=viresh --no-merges $1 ; }
mypatchcount() { glo  --author=viresh --no-merges $1 | wc -l; }
mypatchcountrank() { gl --no-merges --format="%aN" $1..$2 | sort | uniq -ic| sort -nr | less; }

#Other tools
alias myspatch='echo "spatch -in_place -include_headers -sp_file setmode.cocci -dir drivers/"'

# Gitmail
alias gitmail='git send-email *.patch'
alias gitmaillinaro='gitmail --cc linaro'
alias gitmailpm='gitmaillinaro --to rafael --cc pm'
alias gitmailsched='gitmaillinaro --cc lkml --to ingo --to peterz'
alias gitmailtimer='gitmaillinaro --cc lkml --to tglx --cc fw'
alias gitmailara='gitmail --to gregl --to alex --cc ara'
alias gitmailarak='gitmail --to gregl --to alex --cc arak'
alias prepcclist='cat 00* | grep Cc | cut -f 2 -d : | sort | uniq > ~/scripts/mycoverletterlist.txt'
